-- Sample course data structure - Add your own descriptions and details via admin panel
-- This creates placeholder entries that you can edit

INSERT INTO programs (title, slug, category, duration, lessons, created_at) VALUES
-- Certificates
('Certificate In Clinical Cardiology', 'certificate-in-clinical-cardiology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Echocardiography', 'certificate-in-echocardiography', 'Certificate', '6 months', 10, NOW()),
('Certificate in Critical Care Medicine', 'certificate-in-critical-care-medicine', 'Certificate', '6 months', 10, NOW()),
('Certificate in Emergency Medicine', 'certificate-in-emergency-medicine', 'Certificate', '6 months', 10, NOW()),
('Certificate In Infertility', 'certificate-in-infertility', 'Certificate', '6 months', 10, NOW()),
('Certificate In Orthopaedics', 'certificate-in-orthopaedics', 'Certificate', '6 months', 10, NOW()),
('Certificate In Diabetology', 'certificate-in-diabetology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Cosmetology', 'certificate-in-cosmetology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Diabetic Foot Care', 'certificate-in-diabetic-foot-care', 'Certificate', '6 months', 10, NOW()),
('Certificate in Clinical Nutrition', 'certificate-in-clinical-nutrition', 'Certificate', '6 months', 10, NOW()),
('Certificate in Family Medicine', 'certificate-in-family-medicine', 'Certificate', '6 months', 10, NOW()),
('Certificate in Dermatology', 'certificate-in-dermatology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Fetal Echocardiography', 'certificate-in-fetal-echocardiography', 'Certificate', '6 months', 10, NOW()),
('Certificate in Rheumatology', 'certificate-in-rheumatology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Neurology', 'certificate-in-neurology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Obstetrics and Gynecology', 'certificate-in-obstetrics-and-gynecology', 'Certificate', '6 months', 10, NOW()),
('Certificate in Pediatrics', 'certificate-in-pediatrics', 'Certificate', '6 months', 10, NOW()),
('Certificate in High-risk Pregnancy', 'certificate-in-high-risk-pregnancy', 'Certificate', '6 months', 10, NOW()),
('Certificate in Hypertension', 'certificate-in-hypertension', 'Certificate', '6 months', 10, NOW()),
('Certificate in Tuberculosis', 'certificate-in-tuberculosis', 'Certificate', '6 months', 10, NOW()),
('Certificate In Advance ART', 'certificate-in-advance-art', 'Certificate', '6 months', 10, NOW()),
('Certificate in Trauma Life Support', 'certificate-in-trauma-life-support', 'Certificate', '3 months', 8, NOW()),
('Certificate in Pain Management', 'certificate-in-pain-management', 'Certificate', '6 months', 10, NOW()),
('Certificate In Basic Gynecological Ultrasound', 'certificate-in-basic-gynecological-ultrasound', 'Certificate', '6 months', 10, NOW()),
('Certificate In Small Part Ultrasound', 'certificate-in-small-part-ultrasound', 'Certificate', '6 months', 10, NOW()),
('Certificate In Abdominal Ultrasound', 'certificate-in-abdominal-ultrasound', 'Certificate', '6 months', 10, NOW()),
('Certificate in Musculoskeletal Ultrasound', 'certificate-in-musculoskeletal-ultrasound', 'Certificate', '6 months', 10, NOW()),

-- Fellowships
('Fellowship in General Laparoscopic Surgery', 'fellowship-in-general-laparoscopic-surgery', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Arthroscopy and Arthroplasty', 'fellowship-in-arthroscopy-and-arthroplasty', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Facial Aesthetic and Cosmetology', 'fellowship-in-facial-aesthetic-and-cosmetology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Pediatric Endocrinology', 'fellowship-in-pediatric-endocrinology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in High-Risk Pregnancy', 'fellowship-in-high-risk-pregnancy', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Fetal Medicine', 'fellowship-in-fetal-medicine', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Spine Surgery', 'fellowship-in-spine-surgery', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Reproductive Medicine', 'fellowship-in-reproductive-medicine', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Minimal Access Surgery', 'fellowship-in-minimal-access-surgery', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Clinical Embryology', 'fellowship-in-clinical-embryology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Cardiothoracic Surgery', 'fellowship-in-cardiothoracic-surgery', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Clinical Hematology', 'fellowship-in-clinical-hematology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Radiology', 'fellowship-in-radiology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Trichology', 'fellowship-in-trichology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Robotic Surgery', 'fellowship-in-robotic-surgery', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Preventive Cardiology', 'fellowship-in-preventive-cardiology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Cosmetic Gynecology', 'fellowship-in-cosmetic-gynecology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Clinical Echocardiography', 'fellowship-in-clinical-echocardiography', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Echocardiography', 'fellowship-in-echocardiography', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Rheumatology', 'fellowship-in-rheumatology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Head and Neck Oncology', 'fellowship-in-head-and-neck-oncology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Pediatrics', 'fellowship-in-pediatrics', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Nephrology', 'fellowship-in-nephrology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Internal Medicine', 'fellowship-in-internal-medicine', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Neonatology', 'fellowship-in-neonatology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Medical Oncology', 'fellowship-in-medical-oncology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Laparoscopy and Hysteroscopy', 'fellowship-in-laparoscopy-and-hysteroscopy', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Interventional Radiology', 'fellowship-in-interventional-radiology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Interventional Cardiology', 'fellowship-in-interventional-cardiology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Spinal Cord Medicine', 'fellowship-in-spinal-cord-medicine', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Pediatric Rheumatology', 'fellowship-in-pediatric-rheumatology', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Pediatric Echocardiography', 'fellowship-in-pediatric-echocardiography', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Pain Management', 'fellowship-in-pain-management', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Orthopedics', 'fellowship-in-orthopedics', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Emergency Medicine', 'fellowship-in-emergency-medicine', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Dermatology', 'fellowship-in-dermatology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Critical Care', 'fellowship-in-critical-care', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Cosmetology and Aesthetic Medicine', 'fellowship-in-cosmetology-and-aesthetic-medicine', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Clinical Cardiology', 'fellowship-in-clinical-cardiology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Arthroscopy and Sports Medicine', 'fellowship-in-arthroscopy-and-sports-medicine', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Arthroplasty', 'fellowship-in-arthroplasty', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Obstetrics and Gynecology', 'fellowship-in-obstetrics-and-gynecology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Gynecologic Oncology', 'fellowship-in-gynecologic-oncology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in GI Endoscopy', 'fellowship-in-gi-endoscopy', 'Fellowship', '1 year', 15, NOW()),
('Fellowship in Cardio Oncology', 'fellowship-in-cardio-oncology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Gastroenterology', 'fellowship-in-gastroenterology', 'Fellowship', '2 years', 20, NOW()),
('Fellowship in Neuroradiology', 'fellowship-in-neuroradiology', 'Fellowship', '2 years', 20, NOW()),

-- PG Diplomas
('PG Diploma In Family medicine', 'pg-diploma-in-family-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Echocardiography', 'pg-diploma-in-echocardiography', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Rheumatology', 'pg-diploma-in-rheumatology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Emergency Medicine', 'pg-diploma-in-emergency-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Orthopaedics', 'pg-diploma-in-orthopaedics', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma In Clinical Cardiology', 'pg-diploma-in-clinical-cardiology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Dermatology', 'pg-diploma-in-dermatology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Sexology', 'pg-diploma-in-sexology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Psychiatric Medicine', 'pg-diploma-in-psychiatric-medicine', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Reproductive medicine', 'pg-diploma-in-reproductive-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma Obstetrics and Gynecology', 'pg-diploma-in-obstetrics-and-gynecology', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Clinical Pathology', 'pg-diploma-in-clinical-pathology', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Pediatrics', 'pg-diploma-in-pediatrics', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Infertility Management', 'pg-diploma-in-infertility-management', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Maternal and Child Health', 'pg-diploma-in-maternal-and-child-health', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Urology', 'pg-diploma-in-urology', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Critical Care Medicine', 'pg-diploma-in-critical-care-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Clinical Embryology', 'pg-diploma-in-clinical-embryology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Clinical Neurology', 'pg-diploma-in-clinical-neurology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Critical Care', 'pg-diploma-in-critical-care', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Diabetes Educator', 'pg-diploma-in-diabetes-educator', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Emergency Medical Services', 'pg-diploma-in-emergency-medical-services', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in ENT', 'pg-diploma-in-ent', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Cosmetology and Aesthetic Medicine', 'pg-diploma-in-cosmetology-and-aesthetic-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Diabetology', 'pg-diploma-in-diabetology', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Internal medicine', 'pg-diploma-in-internal-medicine', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in HIV Medicine', 'pg-diploma-in-hiv-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Laboratory Medicine', 'pg-diploma-in-laboratory-medicine', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Anesthesiology', 'pg-diploma-in-anesthesiology', 'PG Diploma', '2 years', 18, NOW()),
('PG Diploma in Reproductive and Child Health', 'pg-diploma-in-reproductive-and-child-health', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Infectious Diseases', 'pg-diploma-in-infectious-diseases', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Intensive Care Medicine', 'pg-diploma-in-intensive-care-medicine', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Pediatric Ultrasound', 'pg-diploma-in-pediatric-ultrasound', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Ultrasonography', 'pg-diploma-in-ultrasonography', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Obs and Gynae Ultrasound', 'pg-diploma-in-obstetrics-and-gynaecology-ultrasound', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma In Ultrasound', 'pg-diploma-in-ultrasound', 'PG Diploma', '1 year', 12, NOW()),
('PG Diploma in Geriatric Medicine', 'pg-diploma-in-geriatric-medicine', 'PG Diploma', '1 year', 12, NOW())

ON CONFLICT (slug) DO NOTHING;

-- Note: After importing, go to Admin Panel to add:
-- - Course descriptions
-- - Eligibility criteria
-- - Fees
-- - Images
-- - Detailed curriculum
